### ISSUE TITLE
Deletion of job from queue does not clear the lock key

### ISSUE THREAD

**Issue by driv3r** [krasnoukhov/sidekiq-middleware#10]
When you try to remove the unique job from within Web UI, the lock key is not cleared from redis. Also the same thing can occur when deleting the job or clearing the whole queue from ruby. Probably one of the solutions would be to extend the sidekiq api to also clear the lock first, or at least gather the locks for unlock. If I will have a spare second I can take a deeper look into it.

**Comment by masterkain** [comment]
using sidekiq-pro: if I stop the sidekiq process while an unique task is running, when I restart sidekiq the job is performed twice. Is this a similar issue?
